version: '3'
services:
    mysql:
        container_name: mysql
        image: mysql/mysql:8.0
    environment:
        MYSQL_DATABASE: ecommerce
        MYSQL_ROOT_PASSWORD: root
        MYSQL_ROOT_HOST: '%'
   ports:
    - "3306:3306"
  
  app:
    image: vicentenvt/ecommerce:latest
    expose:
      - "8080"
    depends_on:
      - mysql
